export const ROUTER={
home:"/",
cola:"/cola",
chips:"/chips",
fastFood:"/fast-food",
about:"/about",
colaInfo:"colainfo",
chipsInfo:"chipsinfo",
fastFoodInfo:"fastfoodinfo",
math:"/math",
plus:"plus",
minus:"minus",
multiply:"multiply",
divide:"divide",
}